FROM node:16-buster-slim@sha256:93c9fc3550f5f7d159f282027228e90e3a7f8bf38544758024f005e82607f546

RUN apt update && apt install netcat -y

RUN mkdir /alephium

COPY ./package.json ./tsconfig.json /alephium
COPY ./lib /alephium/lib
COPY ./auto-mine.sh /alephium
COPY .env /alephium

WORKDIR /alephium
RUN npm install

entrypoint ["sh", "/alephium/auto-mine.sh", "alephium"]