/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as AttestTokenHandlerContractJson } from "../token_bridge/attest_token_handler.ral.json";

// Custom types for the contract
export namespace AttestTokenHandlerTypes {
  export type Fields = {
    governance: HexString;
    localTokenBridge: HexString;
    targetChainId: bigint;
    targetTokenBridge: HexString;
    receivedSequence: bigint;
    isLocalHandler: boolean;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  AttestTokenHandlerInstance,
  AttestTokenHandlerTypes.Fields
> {
  at(address: string): AttestTokenHandlerInstance {
    return new AttestTokenHandlerInstance(address);
  }

  tests = {
    parseAttestToken: async (
      params: TestContractParams<
        AttestTokenHandlerTypes.Fields,
        { vaa: HexString }
      >
    ): Promise<
      TestContractResult<[HexString, HexString, HexString, bigint, bigint]>
    > => {
      return testMethod(this, "parseAttestToken", params);
    },
    createLocalTokenPool: async (
      params: TestContractParams<
        AttestTokenHandlerTypes.Fields,
        {
          vaa: HexString;
          payer: Address;
          createContractAlphAmount: bigint;
          tokenAmount: bigint;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createLocalTokenPool", params);
    },
    createRemoteTokenPool: async (
      params: TestContractParams<
        AttestTokenHandlerTypes.Fields,
        { vaa: HexString; payer: Address; createContractAlphAmount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createRemoteTokenPool", params);
    },
    updateRemoteTokenPool: async (
      params: TestContractParams<
        AttestTokenHandlerTypes.Fields,
        { vaa: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "updateRemoteTokenPool", params);
    },
    bytes32ToString: async (
      params: TestContractParams<
        AttestTokenHandlerTypes.Fields,
        { bytes: HexString }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "bytes32ToString", params);
    },
  };
}

// Use this object to test and deploy the contract
export const AttestTokenHandler = new Factory(
  Contract.fromJson(
    AttestTokenHandlerContractJson,
    "",
    "6843ddbf3274d272def615b415c65ee14b9b1171cd49636010a6a547f221b23b"
  )
);

// Use this class to interact with the blockchain
export class AttestTokenHandlerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AttestTokenHandlerTypes.State> {
    return fetchContractState(AttestTokenHandler, this);
  }
}
