/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as TokenBridgeFactoryContractJson } from "../token_bridge/token_bridge_factory.ral.json";

// Custom types for the contract
export namespace TokenBridgeFactoryTypes {
  export type Fields = {
    localTokenPoolTemplateId: HexString;
    remoteTokenPoolTemplateId: HexString;
    tokenBridgeForChainTemplateId: HexString;
    attestTokenHandlerTemplateId: HexString;
    unexecutedSequenceTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getLocalTokenPoolTemplateId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getRemoteTokenPoolTemplateId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getTokenBridgeForChainTemplateId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getAttestTokenHandlerTemplateId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getUnexecutedSequenceTemplateId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  TokenBridgeFactoryInstance,
  TokenBridgeFactoryTypes.Fields
> {
  at(address: string): TokenBridgeFactoryInstance {
    return new TokenBridgeFactoryInstance(address);
  }

  tests = {
    getLocalTokenPoolTemplateId: async (
      params: Omit<
        TestContractParams<TokenBridgeFactoryTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getLocalTokenPoolTemplateId", params);
    },
    getRemoteTokenPoolTemplateId: async (
      params: Omit<
        TestContractParams<TokenBridgeFactoryTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getRemoteTokenPoolTemplateId", params);
    },
    getTokenBridgeForChainTemplateId: async (
      params: Omit<
        TestContractParams<TokenBridgeFactoryTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenBridgeForChainTemplateId", params);
    },
    getAttestTokenHandlerTemplateId: async (
      params: Omit<
        TestContractParams<TokenBridgeFactoryTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getAttestTokenHandlerTemplateId", params);
    },
    getUnexecutedSequenceTemplateId: async (
      params: Omit<
        TestContractParams<TokenBridgeFactoryTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getUnexecutedSequenceTemplateId", params);
    },
  };
}

// Use this object to test and deploy the contract
export const TokenBridgeFactory = new Factory(
  Contract.fromJson(
    TokenBridgeFactoryContractJson,
    "",
    "b08890fe7fe29e80e21a7929ffd4a2658df0928fa1cdb5c45d63a90c55144b8f"
  )
);

// Use this class to interact with the blockchain
export class TokenBridgeFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenBridgeFactoryTypes.State> {
    return fetchContractState(TokenBridgeFactory, this);
  }

  methods = {
    getLocalTokenPoolTemplateId: async (
      params?: TokenBridgeFactoryTypes.CallMethodParams<"getLocalTokenPoolTemplateId">
    ): Promise<
      TokenBridgeFactoryTypes.CallMethodResult<"getLocalTokenPoolTemplateId">
    > => {
      return callMethod(
        TokenBridgeFactory,
        this,
        "getLocalTokenPoolTemplateId",
        params === undefined ? {} : params
      );
    },
    getRemoteTokenPoolTemplateId: async (
      params?: TokenBridgeFactoryTypes.CallMethodParams<"getRemoteTokenPoolTemplateId">
    ): Promise<
      TokenBridgeFactoryTypes.CallMethodResult<"getRemoteTokenPoolTemplateId">
    > => {
      return callMethod(
        TokenBridgeFactory,
        this,
        "getRemoteTokenPoolTemplateId",
        params === undefined ? {} : params
      );
    },
    getTokenBridgeForChainTemplateId: async (
      params?: TokenBridgeFactoryTypes.CallMethodParams<"getTokenBridgeForChainTemplateId">
    ): Promise<
      TokenBridgeFactoryTypes.CallMethodResult<"getTokenBridgeForChainTemplateId">
    > => {
      return callMethod(
        TokenBridgeFactory,
        this,
        "getTokenBridgeForChainTemplateId",
        params === undefined ? {} : params
      );
    },
    getAttestTokenHandlerTemplateId: async (
      params?: TokenBridgeFactoryTypes.CallMethodParams<"getAttestTokenHandlerTemplateId">
    ): Promise<
      TokenBridgeFactoryTypes.CallMethodResult<"getAttestTokenHandlerTemplateId">
    > => {
      return callMethod(
        TokenBridgeFactory,
        this,
        "getAttestTokenHandlerTemplateId",
        params === undefined ? {} : params
      );
    },
    getUnexecutedSequenceTemplateId: async (
      params?: TokenBridgeFactoryTypes.CallMethodParams<"getUnexecutedSequenceTemplateId">
    ): Promise<
      TokenBridgeFactoryTypes.CallMethodResult<"getUnexecutedSequenceTemplateId">
    > => {
      return callMethod(
        TokenBridgeFactory,
        this,
        "getUnexecutedSequenceTemplateId",
        params === undefined ? {} : params
      );
    },
  };

  async multicall<Calls extends TokenBridgeFactoryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TokenBridgeFactoryTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      TokenBridgeFactory,
      this,
      calls
    )) as TokenBridgeFactoryTypes.MultiCallResults<Calls>;
  }
}
