/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as TokenBridgeForChainContractJson } from "../token_bridge/token_bridge_for_chain.ral.json";

// Custom types for the contract
export namespace TokenBridgeForChainTypes {
  export type Fields = {
    governance: HexString;
    localChainId: bigint;
    localTokenBridgeId: HexString;
    remoteChainId: bigint;
    remoteTokenBridgeId: HexString;
    start: bigint;
    firstNext256: bigint;
    secondNext256: bigint;
    unexecutedSequenceTemplateId: HexString;
    sendSequence: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    nextSendSequence: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  TokenBridgeForChainInstance,
  TokenBridgeForChainTypes.Fields
> {
  at(address: string): TokenBridgeForChainInstance {
    return new TokenBridgeForChainInstance(address);
  }

  tests = {
    setExecuted: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { offset: bigint; current: bigint }
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "setExecuted", params);
    },
    compact: async (
      params: Omit<
        TestContractParams<TokenBridgeForChainTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "compact", params);
    },
    checkSequenceInSubContract: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { seq: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "checkSequenceInSubContract", params);
    },
    checkSequence: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { seq: bigint }
      >
    ): Promise<TestContractResult<boolean>> => {
      return testMethod(this, "checkSequence", params);
    },
    nextSendSequence: async (
      params: Omit<
        TestContractParams<TokenBridgeForChainTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "nextSendSequence", params);
    },
    checkCompleteTransfer: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { vaa: HexString }
      >
    ): Promise<TestContractResult<[boolean, HexString]>> => {
      return testMethod(this, "checkCompleteTransfer", params);
    },
    parseCompleteTransfer: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { payload: HexString }
      >
    ): Promise<
      TestContractResult<[bigint, HexString, bigint, Address, bigint]>
    > => {
      return testMethod(this, "parseCompleteTransfer", params);
    },
    completeTransfer: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { vaa: HexString; caller: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "completeTransfer", params);
    },
    destroyUnexecutedSequenceContracts: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { paths: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroyUnexecutedSequenceContracts", params);
    },
    deposit: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { from: Address; alphAmount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "deposit", params);
    },
    withdraw: async (
      params: TestContractParams<
        TokenBridgeForChainTypes.Fields,
        { alphAmount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const TokenBridgeForChain = new Factory(
  Contract.fromJson(
    TokenBridgeForChainContractJson,
    "",
    "4ba106c0803a7a36c9fe4bc7333a10337cf417c8b7155cce01794e4f13aa5d5a"
  )
);

// Use this class to interact with the blockchain
export class TokenBridgeForChainInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenBridgeForChainTypes.State> {
    return fetchContractState(TokenBridgeForChain, this);
  }

  methods = {
    nextSendSequence: async (
      params?: TokenBridgeForChainTypes.CallMethodParams<"nextSendSequence">
    ): Promise<
      TokenBridgeForChainTypes.CallMethodResult<"nextSendSequence">
    > => {
      return callMethod(
        TokenBridgeForChain,
        this,
        "nextSendSequence",
        params === undefined ? {} : params
      );
    },
  };

  async multicall<Calls extends TokenBridgeForChainTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TokenBridgeForChainTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      TokenBridgeForChain,
      this,
      calls
    )) as TokenBridgeForChainTypes.MultiCallResults<Calls>;
  }
}
