{
 "title": "Wormhole (V2)",
 "description": "Wormhole v2",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "ETH Blocks/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wormhole_eth_current_height{eth_network=\"eth\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "ALPH blocks/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wormhole_alph_current_height{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Network ETH Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wormhole_network_node_height{network=\"ethereum\"}"
    }
   ]
  },
  {
   "title": "Network ALPH Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wormhole_network_node_height{network=\"alephium\"}"
    }
   ]
  },
  {
   "title": "Ethereum Query Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(wormhole_eth_query_latency_bucket{}[$__interval])) by (le)"
    }
   ]
  },
  {
   "title": "ALPH Query Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(wormhole_alph_query_latency_bucket{}[$__interval])) by (le)"
    }
   ]
  },
  {
   "title": "Aggregation Cleanup State Machine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_aggregation_state_unobserved_total{}[$__rate_interval])",
     "legendFormat": "unobserved"
    },
    {
     "expr": "increase(wormhole_aggregation_state_expirations_total{}[$__rate_interval])",
     "legendFormat": "expirations"
    },
    {
     "expr": "increase(wormhole_aggregation_state_retries_total{}[$__rate_interval])",
     "legendFormat": "retries"
    },
    {
     "expr": "sum without (addr, origin, status)(increase(wormhole_aggregation_state_settled_signatures_total{}[$__rate_interval]))",
     "legendFormat": "settled"
    },
    {
     "expr": "increase(wormhole_aggregation_state_timeout_total{}[$__rate_interval])",
     "legendFormat": "timeout"
    },
    {
     "expr": "increase(wormhole_aggregation_state_timeout_total{}[$__rate_interval])",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Aggregation State Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wormhole_aggregation_state_entries{}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Message Observations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_eth_messages_observed_total{}[$__rate_interval])",
     "legendFormat": "ethereum (found)"
    },
    {
     "expr": "increase(wormhole_eth_messages_confirmed_total{}[$__rate_interval])",
     "legendFormat": "ethereum (confirmed)"
    }
   ]
  },
  {
   "title": "P2P Messages Received/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wormhole_p2p_broadcast_messages_received_total{}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Watcher Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_eth_connection_errors_total{}[$__rate_interval])",
     "legendFormat": "[Ethereum] {{eth_network}} {{ reason }}"
    },
    {
     "expr": "increase(wormhole_alephium_connection_errors_total{}[$__rate_interval])",
     "legendFormat": "[Alephium]"
    }
   ]
  },
  {
   "title": "Number of Guardians",
   "type": "stat",
   "description": "Number of connected peers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wormhole_guardian_set_signers" }
   ]
  },
  {
   "title": "Observations",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "wormhole_message_observations_signed_total",
     "legendFormat": "Signed"
    },
    {
     "expr": "wormhole_message_observations_total",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Observations by Guardian",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_observations_signed_by_guardian_total{}[$__rate_interval])",
     "legendFormat": "{{ addr }}"
    }
   ]
  },
  {
   "title": "Missing Signatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wormhole_aggregation_state_settled_signatures_total{status!=\"present\"}[1h])",
     "legendFormat": "{{ addr }} [from {{ origin }}]"
    }
   ]
  }
 ]
}