version: "3.3"

volumes:
  alephium-wallets: {}
  eth-full-node: {}
  guardian-node: {}

services:
  alephium:
    image: alephium/dev-alephium:1.5.2
    restart: unless-stopped
    ports:
      - 19973:19973/tcp

      - 19973:19973/udp
      - 127.0.0.1:20973:20973
      - 127.0.0.1:21973:21973
      - 127.0.0.1:22973:22973
    environment:
      - ALEPHIUM_LOG_LEVEL=DEBUG
      - ALEPHIUM_ENABLE_DEBUG_LOGGING=true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./devnet.conf:/alephium-home/.alephium/user.conf
      - alephium-wallets:/alephium-home/.alephium-wallets

  alephium-mine:
    image: alephium/automine:0.2.47
    restart: unless-stopped

  eth-devnet:
    image: alephium/eth-node:0.2.47
    restart: unless-stopped
    user: root
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - eth-full-node:/eth-full-node/
    command:
      - npx
      - ganache-cli
      - --networkId=123456
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
      - --db=/eth-full-node/

  eth-devnet-mine:
    image: alephium/eth-node:0.2.47
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "npx truffle exec mine.js"

  eth-devnet-deploy-contracts:
    image: alephium/eth-node:0.2.47
    command:
      - /bin/sh
      - -c
      - "npm run migrate && npx truffle exec scripts/deploy_test_token.js && npx truffle exec scripts/register_bsc_chain.js && npx truffle exec scripts/register_alph_chain.js"

  guardian-0:
    image: alephium/guardiand:0.2.47
    hostname: guardian-0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8999:8999
      - 127.0.0.1:7070:7070
      - 127.0.0.1:7071:7071
      - 127.0.0.1:6060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --alphRPC
      - http://alephium:22973
      - --alphContractIds
      - "2Ac65oYLMeatxePjYTZwKbBpVXwgHHsJfa5NvLL81mPHM,xoZSoaseF3K6rtw8Lw5dXfJGb9pXYJ3CbDVazLHo6ihU"
      - --alphGroupIndex
      - "0"
      - --alphMinConfirmations
      - "1"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "0"
      - --integrationTest
      - --unsafeDevMode
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  guardian-1:
    image: alephium/guardiand:0.2.47
    hostname: guardian-1
    restart: unless-stopped
    ports:
      - 127.0.0.1:9999:8999
      - 127.0.0.1:8070:7070
      - 127.0.0.1:8071:7071
      - 127.0.0.1:7060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --alphRPC
      - http://alephium:22973
      - --alphContractIds
      - "2Ac65oYLMeatxePjYTZwKbBpVXwgHHsJfa5NvLL81mPHM,xoZSoaseF3K6rtw8Lw5dXfJGb9pXYJ3CbDVazLHo6ihU"
      - --alphGroupIndex
      - "0"
      - --alphMinConfirmations
      - "1"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "1"
      - --integrationTest
      - --unsafeDevMode
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  spy:
    image: alephium/guardiand:0.2.47
    restart: unless-stopped
    ports:
      - 127.0.0.1:7072:7072
    entrypoint:
      - /guardiand
      - spy
      - --nodeKey
      - /tmp/node.key
      - --spyRPC
      - "[::]:7072"
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --logLevel=debug
