version: "3.3"

volumes:
  eth-full-node: {}
  guardian-node: {}

services:
  alph-full-node:
    image: alephium/alephium-contracts:0.2.78
    restart: unless-stopped
    ports:
      - 19973:19973/tcp

      - 19973:19973/udp
      - 127.0.0.1:20973:20973
      - 127.0.0.1:21973:21973
      - 127.0.0.1:22973:22973
    security_opt:
      - no-new-privileges:true
    command:
      - /bin/sh
      - -c
      - "npx @alephium/cli devnet start && sh /alephium/deploy.sh"

  eth-devnet:
    image: alephium/eth-node:0.2.78
    restart: unless-stopped
    user: root
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - eth-full-node:/eth-full-node/
    command:
      - npx
      - ganache-cli
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
      - --db=/eth-full-node/

  eth-devnet-deploy-contracts:
    image: alephium/eth-node:0.2.78
    command:
      - /bin/sh
      - -c
      - "cd .. && git apply ./ethereum/1conf.patch && cd ethereum && npm run migrate -- --network docker && npx truffle exec mine.js --network docker"

  devnet-init:
    image: alephium/devnet-init:0.2.78
    command:
      - /bin/sh
      - -c
      - "/scripts/devnet-init.sh 1"

  guardian-0:
    image: alephium/guardiand:0.2.78
    hostname: guardian-0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8999:8999
      - 127.0.0.1:7070:7070
      - 127.0.0.1:7071:7071
      - 127.0.0.1:6060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --alphRPC
      - http://alph-full-node:22973
      - --alphContractIds
      - "2Ac65oYLMeatxePjYTZwKbBpVXwgHHsJfa5NvLL81mPHM,xoZSoaseF3K6rtw8Lw5dXfJGb9pXYJ3CbDVazLHo6ihU"
      - --alphGroupIndex
      - "0"
      - --alphMinConfirmations
      - "1"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "0"
      - --integrationTest
      - --unsafeDevMode
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  guardian-1:
    image: alephium/guardiand:0.2.78
    hostname: guardian-1
    restart: unless-stopped
    ports:
      - 127.0.0.1:9999:8999
      - 127.0.0.1:8070:7070
      - 127.0.0.1:8071:7071
      - 127.0.0.1:7060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --alphRPC
      - http://alph-full-node:22973
      - --alphContractIds
      - "2Ac65oYLMeatxePjYTZwKbBpVXwgHHsJfa5NvLL81mPHM,xoZSoaseF3K6rtw8Lw5dXfJGb9pXYJ3CbDVazLHo6ihU"
      - --alphGroupIndex
      - "0"
      - --alphMinConfirmations
      - "1"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "1"
      - --integrationTest
      - --unsafeDevMode
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  spy:
    image: alephium/guardiand:0.2.78
    restart: unless-stopped
    ports:
      - 127.0.0.1:7072:7072
    entrypoint:
      - /guardiand
      - spy
      - --nodeKey
      - /tmp/node.key
      - --spyRPC
      - "[::]:7072"
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --logLevel=debug
