version: "3.3"

volumes:
  eth-full-node: {}
  bsc-full-node: {}
  guardian-node: {}

services:
  alph-full-node:
    image: eu.gcr.io/alephium-org/alephium-contracts:0.2.121
    restart: unless-stopped
    ports:
      - 19973:19973/tcp

      - 19973:19973/udp
      - 127.0.0.1:20973:20973
      - 127.0.0.1:21973:21973
      - 127.0.0.1:22973:22973
    security_opt:
      - no-new-privileges:true
    command:
      - /bin/sh
      - -c
      - "npx @alephium/cli devnet start && sh /alephium/deploy.sh"

  eth-devnet:
    image: eu.gcr.io/alephium-org/eth-node:0.2.121
    restart: unless-stopped
    user: root
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - eth-full-node:/eth-full-node/
    command:
      - npx
      - ganache-cli
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
      - --db=/eth-full-node/

  eth-devnet-deploy-contracts:
    image: eu.gcr.io/alephium-org/eth-node:0.2.121
    command:
      - /bin/sh
      - -c
      - "cd .. && git apply ./ethereum/1conf.patch && cd ethereum && CHAIN_NAME=ethereum npm run migrate -- --network ethDocker && npx truffle exec mine.js --network ethDocker"

  bsc-devnet:
    image: eu.gcr.io/alephium-org/eth-node:0.2.121
    restart: unless-stopped
    user: root
    ports:
      - 127.0.0.1:8546:8545
    volumes:
      - bsc-full-node:/bsc-full-node/
    command:
      - npx
      - ganache-cli
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
      - --db=/bsc-full-node/

  bsc-devnet-deploy-contracts:
    image: eu.gcr.io/alephium-org/eth-node:0.2.121
    command:
      - /bin/sh
      - -c
      - "cd .. && git apply ./ethereum/1conf.patch && cd ethereum && CHAIN_NAME=bsc npm run migrate -- --network bscDocker && npx truffle exec mine.js --network bscDocker"

  devnet-init:
    image: eu.gcr.io/alephium-org/devnet-init:0.2.121
    command:
      - /bin/sh
      - -c
      - "/scripts/devnet-init.sh 1"

  guardian-0:
    image: eu.gcr.io/alephium-org/guardiand:0.2.121
    hostname: guardian-0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8999:8999/udp
      - 127.0.0.1:7070:7070
      - 127.0.0.1:7071:7071
      - 127.0.0.1:6060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --bscRPC
      - ws://bsc-devnet:8545
      - --alphRPC
      - http://alph-full-node:22973
      - --network
      - "devnet"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "0"
      - --integrationTest
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  guardian-1:
    image: eu.gcr.io/alephium-org/guardiand:0.2.121
    hostname: guardian-1
    restart: unless-stopped
    ports:
      - 127.0.0.1:9999:8999/udp
      - 127.0.0.1:8070:7070
      - 127.0.0.1:8071:7071
      - 127.0.0.1:7060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --bscRPC
      - ws://bsc-devnet:8545
      - --alphRPC
      - http://alph-full-node:22973
      - --network
      - "devnet"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "1"
      - --integrationTest
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  guardian-2:
    image: eu.gcr.io/alephium-org/guardiand:0.2.121
    hostname: guardian-2
    restart: unless-stopped
    ports:
      - 127.0.0.1:10999:8999/udp
      - 127.0.0.1:9070:7070
      - 127.0.0.1:9071:7071
      - 127.0.0.1:8060:6060
    volumes:
      - guardian-node:/run/node/data
    entrypoint:
      - /guardiand
      - node
      - --ethRPC
      - ws://eth-devnet:8545
      - --bscRPC
      - ws://bsc-devnet:8545
      - --alphRPC
      - http://alph-full-node:22973
      - --network
      - "devnet"
      - --alphFetchPeriod
      - "1"
      - --devnetGuardianIndex
      - "2"
      - --integrationTest
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --logLevel=debug

  spy:
    image: eu.gcr.io/alephium-org/guardiand:0.2.121
    restart: unless-stopped
    ports:
      - 127.0.0.1:7072:7072
    entrypoint:
      - /guardiand
      - spy
      - --nodeKey
      - /tmp/node.key
      - --spyRPC
      - "[::]:7072"
      - --bootstrap
      - "/dns4/guardian-0/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw"
      - --logLevel=debug

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
