[package]
name = "solitaire-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "=1.9.4"
solana-program = "=1.9.4"
solitaire = {path = "../program", features = ["no-entrypoint"]}
borsh = "=0.9.1"
