name: Audit
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  alephium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run audit
        working-directory: ./alephium
        run: npm audit --production

  sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run audit
        working-directory: ./sdk/js
        run: npm audit --production