name: Integration Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - build-docker-images
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.6'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: build docker images
        run: ./build-docker-images.sh "devnet"
      - name: start docker images
        working-directory: ./integration_test/docker
        run: docker-compose up -d
      - name: wait until contracts are deployed
        working-directory: ./integration_test/docker
        run: ./wait-until-services-up.sh
      - name: build clients
        working-directory: ./clients/js
        run: npm install && npm run build
      - name: run integration test
        working-directory: ./integration_test
        run: npm install && npm run it
      - name: Collect Docker Logs
        if: success() || failure()
        uses: jwalton/gh-docker-logs@v2.2.1
      # Next publish docker images after integration tests pass
