name: Integration Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - refactor-configs
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.6'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: build devnet docker images
        run: ./build-docker-images.sh "devnet"
      - name: docker system prune
        run: docker system prune -f
      - name: start docker images
        working-directory: ./docker
        run: MONGO_USER=root MONGO_PASSWORD=root docker-compose up -d
      - name: wait until contracts are deployed
        working-directory: ./docker
        run: ./wait-until-services-up.sh
      - name: build clients
        working-directory: ./clients/js
        run: npm install && npm run build
      - name: run integration test
        working-directory: ./integration_test
        run: npm install && npm run it
      - name: run relayer integration test
        working-directory: ./relayer-engine
        run: |
          npm install && npm run build
          npm run start:devnet &
          sleep 5 && npm run test
      - name: Collect Docker Logs
        if: success() || failure()
        uses: jwalton/gh-docker-logs@v2.2.1
      # Next publish docker images after integration tests pass
  publish:
    needs: test
    runs-on: ubuntu-20.04  
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: projects/1004240933630/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: wormhole-fork-repo@alephium-org.iam.gserviceaccount.com
    - name: auth docker
      run: gcloud auth configure-docker
    - name: build and push testnet docker images
      run: ./build-docker-images.sh "testnet" true
