name: Publish Docker Images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
  workflow_dispatch:

jobs:
  get_dist_tag:
    runs-on: ubuntu-latest
    outputs:
      DIST_TAG: ${{ steps.get_tag.outputs.DIST_TAG }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Get the tag name
        id: get_tag
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?$ ]]; then
            echo "DIST_TAG=$tag" >> $GITHUB_OUTPUT
          else
            echo "Invalid tag format: $tag" >&2
            exit 1
          fi
        shell: bash
  publish:
    runs-on: ubuntu-latest
    needs: get_dist_tag
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: projects/1004240933630/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: wormhole-fork-repo@alephium-org.iam.gserviceaccount.com
    - name: auth docker
      run: gcloud auth configure-docker
    - name: build and push mainnet docker images
      run: ./build-docker-images.sh "mainnet" ${{ needs.get_dist_tag.outputs.DIST_TAG }} true
