name: Test gcloud
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - refactor-configs
      - refactor-configs-u

jobs:
  publish:
    runs-on: ubuntu-20.04    
    permissions:
      id-token: write
      contents: read
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: projects/alephium-org/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: wormhole-fork-repo@alephium-org.iam.gserviceaccount.com
    - name: auth docker
      run: gcloud auth configure-docker
    - name: pull images
      run: gcloud storage ls --project=alephium-org
