name: Unit Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  # Verify whether the Makefile builds the node (no dependencies other than Go)
  node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.6'
      - run: make node && make guardian-test

  ethereum:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd ethereum && make test

  alephium:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        working-directory: ./alephium
        run: |
          npm ci
          npm run build
          cp .env.test .env
          npm run lint
          npx @alephium/cli devnet start
          npm test
          npx @alephium/cli devnet stop

  sdk:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.6'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        working-directory: .
        run: |
          cd tools && npm ci && cd ..
          make generate-proto-sdk
          cd ethereum && npm ci && npm run build
          cd ../sdk/js
          npm ci && npm run build && npm run test
