---
apiVersion: v1
kind: Service
metadata:
  name: alph-full-node
  labels:
    app: alph-full-node
spec:
  type: ClusterIP
  selector:
    app: alph-full-node
  ports:
  - name: alph-rest
    port: 22973
    targetPort: alph-rest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alph-full-node
spec:
  selector:
    matchLabels:
      app: alph-full-node
  serviceName: alph-full-node
  template:
    metadata:
      labels:
        app: alph-full-node
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
        - name: alph-full-node
          image: alephium
          command: ["/bin/sh", "-c"]
          args:
            - npx @alephium/cli devnet start && sh /alephium/deploy.sh;
          ports:
            - containerPort: 22973
              name: alph-rest
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 22973
