apiVersion: v1
kind: Service
metadata:
  name: bsc-devnet
  labels:
    app: bsc-devnet
spec:
  ports:
    - port: 8545
      name: rpc
      protocol: TCP
  clusterIP: None
  selector:
    app: bsc-devnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bsc-devnet
spec:
  selector:
    matchLabels:
      app: bsc-devnet
  serviceName: bsc-devnet
  replicas: 1
  template:
    metadata:
      labels:
        app: bsc-devnet
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: ganache
          image: eth-node
          command:
            - npx
            - ganache-cli
            - -e 10000
            - --deterministic
            - --time $(date -u +%Y-%m-%dT%H:%M:%S%:z)
            - --host=0.0.0.0
            - --chainId=1397
          ports:
            - containerPort: 8545
              name: rpc
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: rpc
        - name: tests
          image: eth-node
          stdin: true
          command:
            - /bin/sh
            - -c
            - "CHAIN_NAME=bsc npm run migrate -- --network devnet && nc -lkp 2000 0.0.0.0"
          readinessProbe:
            periodSeconds: 1
            failureThreshold: 300
            tcpSocket:
              port: 2000
        - name: mine
          image: eth-node
          command:
            - /bin/sh
            - -c
            - "npx truffle exec mine.js --network devnet"
