---
apiVersion: v1
kind: Service
metadata:
  name: fly
  labels:
    app: fly
spec:
  clusterIP: None
  selector:
    app: fly
  ports:
    - port: 8101
      name: fly
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fly
spec:
  selector:
    matchLabels:
      app: fly
  serviceName: fly
  template:
    metadata:
      labels:
        app: fly
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
        - name: fly
          image: fly:latest
          command:
            - /fly
            - --bootstrap
            - /dns4/guardian-0.guardian/udp/8999/quic/p2p/12D3KooWL3XJ9EMCyZvmmGXL2LMiVBtrVa2BuESsJiXkSj7333Jw
            - --guardianGrpcUrl
            - guardian-0.guardian:7070
            - --ethRpcUrl
            - ws://eth-devnet:8545
            - --mongodbUri
            - mongodb://mongo-0.mongo/?replicaSet=rs0
            - --mongodbName
            - explorer-devnet
            - --network
            - "devnet"
            - --p2pPort
            - "10999"
            - --apiPort
            - "8101"
            - --nodeKey
            - /tmp/node.key
            - --logLevel=debug
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8101
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          ports:
            - containerPort: 8101
              name: server
              protocol: TCP