---
apiVersion: v1
kind: Service
metadata:
  name: indexer-api
  labels:
    app: indexer-api
spec:
  clusterIP: None
  selector:
    app: indexer-api
  ports:
    - port: 8100
      name: indexer-api
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-api
spec:
  selector:
    matchLabels:
      app: indexer-api
  template:
    metadata:
      labels:
        app: indexer-api
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
        - name: indexer-api
          image: indexer-api:latest
          command:
            - /api
            - --mongodbUri
            - mongodb://mongo-0.mongo/?replicaSet=rs0
            - --mongodbName
            - explorer-devnet
            - --port
            - "8100"
            - --logLevel=debug
            - --enableCache=false
            - --enableStackTrace=true
          env:
            - name: WORMSCAN_DB_URL
              value: mongodb://mongo-0.mongo/?replicaSet=rs0
            - name: WORMSCAN_PORT
              value: "8100"
            - name: WORMSCAN_CACHE_ENABLED
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8100
            periodSeconds: 1
            failureThreshold: 300
          ports:
            - containerPort: 8100
              name: server
              protocol: TCP